name = "worker-test"
main = "src/index.ts"
compatibility_date = "2024-09-24"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "8f33c7fd77d742ceb55554795b0e8bfe"
preview_id = "8f33c7fd77d742ceb55554795b0e8bfe"

[[d1_databases]]
binding = "D1_DATABASE"
database_id = "cfd25068-89f5-43ef-a67b-8b00c07b6bda"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "llmptestvectorize"